# Generated by Django 3.2.9 on 2021-11-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonemanage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='phonenumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('department', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('identity', models.CharField(max_length=20)),
            ],
        ),
    ]
